# Generated by Django 3.2.11 on 2022-01-28 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internalID', models.IntegerField(verbose_name='Cat serial number from the csv')),
                ('Name', models.CharField(max_length=100, verbose_name='Name of the cat')),
                ('Breed', models.CharField(max_length=100, verbose_name='Breed of the cat')),
                ('Birth', models.DateField(verbose_name='Birthdate of the cat')),
                ('Gender', models.CharField(max_length=100, verbose_name='Gender of the cat')),
                ('Fur', models.CharField(max_length=100, verbose_name='Fur code of the cat')),
                ('Number', models.CharField(max_length=200, verbose_name='Identification number of the cat')),
                ('Title', models.CharField(max_length=50, verbose_name='Titles of the cat')),
                ('Father', models.CharField(max_length=200, verbose_name='Identification of the Father of the cat')),
                ('Mother', models.CharField(max_length=200, verbose_name='Identification of the Mother of the cat')),
                ('From', models.CharField(max_length=20, verbose_name='Site from which the cat is from')),
            ],
        ),
    ]
