# Generated by Django 3.2.11 on 2022-01-28 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cat',
            old_name='Birth',
            new_name='birth',
        ),
        migrations.RenameField(
            model_name='cat',
            old_name='Breed',
            new_name='breed',
        ),
        migrations.RenameField(
            model_name='cat',
            old_name='Father',
            new_name='father',
        ),
        migrations.RenameField(
            model_name='cat',
            old_name='Fur',
            new_name='fur',
        ),
        migrations.RenameField(
            model_name='cat',
            old_name='Gender',
            new_name='gender',
        ),
        migrations.RenameField(
            model_name='cat',
            old_name='internalID',
            new_name='internalid',
        ),
        migrations.RenameField(
            model_name='cat',
            old_name='Mother',
            new_name='mother',
        ),
        migrations.RenameField(
            model_name='cat',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='cat',
            old_name='Number',
            new_name='number',
        ),
        migrations.RenameField(
            model_name='cat',
            old_name='From',
            new_name='site',
        ),
        migrations.RenameField(
            model_name='cat',
            old_name='Title',
            new_name='title',
        ),
    ]
