# Generated by Django 3.2.11 on 2022-01-28 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catapp', '0002_auto_20220128_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat',
            name='birth',
            field=models.DateField(null=True, verbose_name='Birthdate of the cat'),
        ),
        migrations.AlterField(
            model_name='cat',
            name='breed',
            field=models.CharField(max_length=100, null=True, verbose_name='Breed of the cat'),
        ),
        migrations.AlterField(
            model_name='cat',
            name='father',
            field=models.CharField(max_length=200, null=True, verbose_name='Identification of the Father of the cat'),
        ),
        migrations.AlterField(
            model_name='cat',
            name='fur',
            field=models.CharField(max_length=100, null=True, verbose_name='Fur code of the cat'),
        ),
        migrations.AlterField(
            model_name='cat',
            name='gender',
            field=models.CharField(max_length=100, null=True, verbose_name='Gender of the cat'),
        ),
        migrations.AlterField(
            model_name='cat',
            name='internalid',
            field=models.IntegerField(null=True, verbose_name='Cat serial number from the csv'),
        ),
        migrations.AlterField(
            model_name='cat',
            name='mother',
            field=models.CharField(max_length=200, null=True, verbose_name='Identification of the Mother of the cat'),
        ),
        migrations.AlterField(
            model_name='cat',
            name='name',
            field=models.CharField(max_length=100, null=True, verbose_name='Name of the cat'),
        ),
        migrations.AlterField(
            model_name='cat',
            name='number',
            field=models.CharField(max_length=200, null=True, verbose_name='Identification number of the cat'),
        ),
        migrations.AlterField(
            model_name='cat',
            name='site',
            field=models.CharField(max_length=20, null=True, verbose_name='Site from which the cat is from'),
        ),
        migrations.AlterField(
            model_name='cat',
            name='title',
            field=models.CharField(max_length=50, null=True, verbose_name='Titles of the cat'),
        ),
    ]
