# Generated by Django 3.2.11 on 2022-01-28 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catapp', '0003_auto_20220128_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat',
            name='name',
            field=models.CharField(max_length=1000, null=True, verbose_name='Name of the cat'),
        ),
    ]
