# Generated by Django 3.2.11 on 2022-02-04 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catapp', '0004_alter_cat_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat',
            name='title',
            field=models.CharField(max_length=100, null=True, verbose_name='Titles of the cat'),
        ),
    ]
