# Generated by Django 3.2.11 on 2022-03-23 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catapp', '0008_appearancecodes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Breeds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CODE', models.CharField(max_length=1000)),
                ('English', models.CharField(max_length=1000)),
                ('Deutsch', models.CharField(max_length=1000)),
                ('Français', models.CharField(max_length=1000)),
            ],
        ),
    ]
