# Generated by Django 3.2.11 on 2022-04-25 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catapp', '0010_catinfo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='catinfo',
            old_name='Français',
            new_name='Francais',
        ),
    ]
