# Generated by Django 3.2.11 on 2022-05-14 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catapp', '0012_alter_catinfo_recognized'),
    ]

    operations = [
        migrations.AddField(
            model_name='cat',
            name='fatherLink',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fatherLink_cat', to='catapp.cat'),
        ),
        migrations.AddField(
            model_name='cat',
            name='motherLink',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='motherLink_cat', to='catapp.cat'),
        ),
    ]
